# Generated by Django 5.2.1 on 2026-06-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelroute',
            name='hotel_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住宿费用'),
        ),
        migrations.AddField(
            model_name='travelroute',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='交通费用'),
        ),
    ]
